### ISSUE TITLE
On DKIM

### ISSUE THREAD

**Issue by defanor** [TheBigBear/saltstack-formulas#1]
Hello,

As a reply to <https://github.com/GoogleChrome/web.dev/issues/5547#issuecomment-859621176>: my email is actually at uberspace.net (not .de, and it's not related to .de), but I've received your message (directed to .net) yesterday, and replied to it (with 2 messages, actually). Since you didn't see it, possibly Gmail had placed it into its spam folder, but a Gmail server accepted it.

If you won't find it in the spam folder, feel free to contact me over XMPP (same as email) or IRC (same login at Libera.chat), or I can simply paste the reply here, if everything else fails and you're fine with it being public.

**Comment by TheBigBear** [comment]
Thanks, your feedback is much appreciated.
